language: php

php:
  - 7.1
  - 7.2

env:
  global:
    - setup=basic

sudo: false

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-source; fi

script: vendor/bin/phpunit --testdox